### ISSUE TITLE
NPM archive broken due to 1.0.5 => 1.1.0 not being a major update

### ISSUE THREAD

**Issue by vankasteelj** [techno-express/node-wget-fetch#2]
Hi, 

I'm using CJS only and had to manuall specify `"node-wget-fetch": "1.0.5",` (although I don't need that dependency directly but it is used by node-7z-forall) because your update to 1.1.0 is a major change as it breaks compatibility with CJS (being ESM only), but is marked as minor change. 

See https://semver.org/ for versionning information: I would advise reverting the rollout of 1.1.0, and release the module as 2.0.0, as you don't support CJS anymore.

**Comment by vankasteelj** [comment]
Or maybe it is the `"type": "module",` mention in https://github.com/techno-express/node-wget-fetch/blob/master/package.json#L5

but anyway, NPM is broken when using any of your deprecated modules, and it doesn't have to be

**Comment by TheTechsTech** [comment]
Thanks, i didn’t realize that would happen.

You can submit PR if you want.

So only this package needs updating, not ‘node-7z-forall’ too?

**Comment by vankasteelj** [comment]
I'm really not used enough to ESM to make a good PR I'm afraid, as I don't know what is exactly wrong. 

What I can say is that : in order to use node-7z-forall, i had to manually add `"node-wget-fetch": "1.0.5",` next to it in package.json, otherwise it tried to download `1.1.0` and I was served with an ESM-related error. Now, is it because of the "type:module" mention? I'm not sure as I've never encountered an ESM module before I saw your new node-7z-archive, which I can't use as I dont want to rewrite every require.

As I understand the situation, there are several options: 

1. Pushing a `2.0.0` node-wget-fetch with the `"type":"module"` in the package.json, and force NPM to remove `1.1.0`, is a way. But it could break the module for people who use it as it the last 10 months, maybe? At least it would fix every possible archive-related scenario (if other modules rely on 1.0.5 and are also broken by this update, I dunno).
1. Release a new node-7z-forall version, enforcing precisely node-wget-fetch `1.0.5`, and not `^1.0.5`, would also fix the issue, but the non-semantic versionning would still be an issue for people expecting to be able to use `^1.0.5` as a dependency. 

Sadly we catch this 10 months after the release, not immediately, which might have been a much simpler situation. Here I feel every option has a catch that will break something for someone somewhere.

**Comment by TheTechsTech** [comment]
It’s seems option 2 might be best, enforce ‘node-7z-forall’ to 1.0.5. 

Yes, I messed up staying consistent on versioning, and this package updates. 

Will push a release by end of today or sometime tomorrow, need to fix both packages for any other conflicts.

**Comment by TheTechsTech** [comment]
I have re enabled [node-7z-foall](https://github.com/techno-express/node-7z-forall) for writes.

**Comment by TheTechsTech** [comment]
I have published new release to NPM.

**Comment by vankasteelj** [comment]
thanks! :) it works fine now. Sorry to disturb you for something you no longer maintain, it felt important for the "archives" to have somethink at least as functionnal as you left it (and thanks for the packages, I've tried many until I fell onto yours that simplifies my life, I use it to bundle mpv automatically)
